// <auto-generated />
using System;
using AgroTechApp.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroTechApp.Migrations
{
    [DbContext(typeof(AgroTechDbContext))]
    partial class AgroTechDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroTechApp.Models.DB.Animal", b =>
                {
                    b.Property<long>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnimalId"));

                    b.Property<string>("Arete")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Activo");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LoteAnimalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MadreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("PadreId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PesoNacimiento")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("RazaId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("AnimalId")
                        .HasName("PK__Animal__A21A73071EEB27B9");

                    b.HasIndex("LoteAnimalId");

                    b.HasIndex("MadreId");

                    b.HasIndex("PadreId");

                    b.HasIndex("RazaId");

                    b.HasIndex(new[] { "FincaId", "Arete" }, "IX_Animal_Finca_Arete");

                    b.HasIndex(new[] { "FincaId", "Arete" }, "UQ__Animal__4F10454D26C1F21C")
                        .IsUnique();

                    b.ToTable("Animal", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.CategoriaInsumo", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1E5D488D06F");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Categori__75E3EFCF786FDE5F")
                        .IsUnique();

                    b.ToTable("CategoriaInsumo", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Finca", b =>
                {
                    b.Property<long>("FincaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FincaId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("FincaId")
                        .HasName("PK__Finca__2CBEEB69224D34AC");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Finca__75E3EFCF4156F071")
                        .IsUnique();

                    b.ToTable("Finca", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Gasto", b =>
                {
                    b.Property<long>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GastoId"));

                    b.Property<long?>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long?>("PotreroId")
                        .HasColumnType("bigint");

                    b.Property<int>("RubroGastoId")
                        .HasColumnType("int");

                    b.HasKey("GastoId")
                        .HasName("PK__Gasto__815BB0F03A3DD153");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("PotreroId");

                    b.HasIndex("RubroGastoId");

                    b.HasIndex(new[] { "FincaId", "Fecha" }, "IX_Gasto_Finca_Fecha");

                    b.ToTable("Gasto", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Ingreso", b =>
                {
                    b.Property<long>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngresoId"));

                    b.Property<long?>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RubroIngresoId")
                        .HasColumnType("int");

                    b.HasKey("IngresoId")
                        .HasName("PK__Ingreso__DBF0909A280B49FC");

                    b.HasIndex("AnimalId");

                    b.HasIndex("RubroIngresoId");

                    b.HasIndex(new[] { "FincaId", "Fecha" }, "IX_Ingreso_Finca_Fecha");

                    b.ToTable("Ingreso", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Insumo", b =>
                {
                    b.Property<long>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsumoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("InsumoId")
                        .HasName("PK__Insumo__C10BE9561AEBE722");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UnidadId");

                    b.HasIndex(new[] { "FincaId", "Nombre" }, "UQ__Insumo__DBE0D59455BFB05C")
                        .IsUnique();

                    b.ToTable("Insumo", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.InsumoLote", b =>
                {
                    b.Property<long>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoteId"));

                    b.Property<string>("CodigoLote")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<long>("InsumoId")
                        .HasColumnType("bigint");

                    b.HasKey("LoteId")
                        .HasName("PK__InsumoLo__E6EAE698D1B6F870");

                    b.HasIndex(new[] { "InsumoId", "CodigoLote" }, "UQ__InsumoLo__0CF73AE1867A482D")
                        .IsUnique()
                        .HasFilter("[CodigoLote] IS NOT NULL");

                    b.ToTable("InsumoLote", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.LoteAnimal", b =>
                {
                    b.Property<long>("LoteAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoteAnimalId"));

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("LoteAnimalId")
                        .HasName("PK__LoteAnim__BB31C7B19E2DFE0B");

                    b.HasIndex(new[] { "FincaId", "Nombre" }, "UQ__LoteAnim__DBE0D594AE887473")
                        .IsUnique();

                    b.ToTable("LoteAnimal", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Mortalidad", b =>
                {
                    b.Property<long>("MortalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MortalidadId"));

                    b.Property<long>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Causa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MortalidadId")
                        .HasName("PK__Mortalid__43C36E9707B3C619");

                    b.HasIndex("AnimalId");

                    b.ToTable("Mortalidad", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.MovimientoAnimal", b =>
                {
                    b.Property<long>("MovAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovAnimalId"));

                    b.Property<long>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("PotreroId")
                        .HasColumnType("bigint");

                    b.HasKey("MovAnimalId")
                        .HasName("PK__Movimien__DC34C30DB5F7E963");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PotreroId");

                    b.ToTable("MovimientoAnimal", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.MovimientoInventario", b =>
                {
                    b.Property<long>("MovId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<long>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("MovId")
                        .HasName("PK__Movimien__C4941F47F78D8641");

                    b.HasIndex("FincaId");

                    b.HasIndex("LoteId");

                    b.HasIndex("TipoId");

                    b.HasIndex(new[] { "InsumoId", "Fecha" }, "IX_MovInv_Insumo_Fecha");

                    b.ToTable("MovimientoInventario", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.PeriodoRetiro", b =>
                {
                    b.Property<long>("RetiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RetiroId"));

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("TratamientoId")
                        .HasColumnType("bigint");

                    b.HasKey("RetiroId")
                        .HasName("PK__PeriodoR__992834D8FCC4B4F1");

                    b.HasIndex("TratamientoId");

                    b.ToTable("PeriodoRetiro", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Pesaje", b =>
                {
                    b.Property<long>("PesajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PesajeId"));

                    b.Property<long>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("PesajeId")
                        .HasName("PK__Pesaje__03DC4C0867DE8B5B");

                    b.HasIndex(new[] { "AnimalId", "Fecha" }, "IX_Pesaje_Animal_Fecha")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "AnimalId", "Fecha" }, "UQ__Pesaje__492ABBA30C060F52")
                        .IsUnique();

                    b.ToTable("Pesaje", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Potrero", b =>
                {
                    b.Property<long>("PotreroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PotreroId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Hectareas")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("PotreroId")
                        .HasName("PK__Potrero__673CB670820876E7");

                    b.HasIndex(new[] { "FincaId", "Nombre" }, "UQ__Potrero__DBE0D5946768C80A")
                        .IsUnique();

                    b.ToTable("Potrero", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Raza", b =>
                {
                    b.Property<int>("RazaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RazaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("RazaId")
                        .HasName("PK__Raza__39A423D838BEA012");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Raza__75E3EFCF0097E82F")
                        .IsUnique();

                    b.ToTable("Raza", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UsuarioCrea")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioModifica")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId")
                        .HasName("PK__Rol__F92302F1F2A4F3A0");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Rol__75E3EFCF9BA8E4C3")
                        .IsUnique();

                    b.ToTable("Rol", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.RubroGasto", b =>
                {
                    b.Property<int>("RubroGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroGastoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("RubroGastoId")
                        .HasName("PK__RubroGas__7FAB05BF701B8B49");

                    b.HasIndex(new[] { "Nombre" }, "UQ__RubroGas__75E3EFCFFA349E2D")
                        .IsUnique();

                    b.ToTable("RubroGasto", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.RubroIngreso", b =>
                {
                    b.Property<int>("RubroIngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroIngresoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("RubroIngresoId")
                        .HasName("PK__RubroIng__4F74782FA8C12E33");

                    b.HasIndex(new[] { "Nombre" }, "UQ__RubroIng__75E3EFCF3BCD2A16")
                        .IsUnique();

                    b.ToTable("RubroIngreso", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.TipoMovimientoInventario", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("TipoId")
                        .HasName("PK__TipoMovi__97099EB7ADD6A42D");

                    b.HasIndex(new[] { "Nombre" }, "UQ__TipoMovi__75E3EFCF87EB3142")
                        .IsUnique();

                    b.ToTable("TipoMovimientoInventario", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.TipoTratamiento", b =>
                {
                    b.Property<int>("TipoTratId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTratId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("TipoTratId")
                        .HasName("PK__TipoTrat__627E84A29673BD4B");

                    b.HasIndex(new[] { "Nombre" }, "UQ__TipoTrat__75E3EFCF1A953E87")
                        .IsUnique();

                    b.ToTable("TipoTratamiento", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Tratamiento", b =>
                {
                    b.Property<long>("TratamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TratamientoId"));

                    b.Property<long?>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Dosis")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LoteAnimalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoTratId")
                        .HasColumnType("int");

                    b.Property<string>("Via")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TratamientoId")
                        .HasName("PK__Tratamie__6CFB22659AC62484");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("LoteAnimalId");

                    b.HasIndex("LoteId");

                    b.HasIndex("TipoTratId");

                    b.HasIndex(new[] { "FincaId", "Fecha" }, "IX_Tratamiento_Finca_Fecha");

                    b.ToTable("Tratamiento", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.UnidadMedidum", b =>
                {
                    b.Property<int>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("UnidadId")
                        .HasName("PK__UnidadMe__C6F324D6B55F7B5A");

                    b.HasIndex(new[] { "Codigo" }, "UQ__UnidadMe__06370DAC4FE9848A")
                        .IsUnique();

                    b.ToTable("UnidadMedida", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte[]>("HashPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CCC96A2F8");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D1053427CA21FA")
                        .IsUnique();

                    b.ToTable("User", "agro");
                });

            modelBuilder.Entity("UserFinca", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FincaId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "FincaId")
                        .HasName("PK__UserFinc__954322FA450C2252");

                    b.HasIndex("FincaId");

                    b.ToTable("UserFinca", "agro");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Animal", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Animals")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Animal__FincaId__797309D9");

                    b.HasOne("AgroTechApp.Models.DB.LoteAnimal", "LoteAnimal")
                        .WithMany("Animals")
                        .HasForeignKey("LoteAnimalId")
                        .HasConstraintName("FK__Animal__LoteAnim__00200768");

                    b.HasOne("AgroTechApp.Models.DB.Animal", "Madre")
                        .WithMany("InverseMadre")
                        .HasForeignKey("MadreId")
                        .HasConstraintName("FK__Animal__MadreId__7E37BEF6");

                    b.HasOne("AgroTechApp.Models.DB.Animal", "Padre")
                        .WithMany("InversePadre")
                        .HasForeignKey("PadreId")
                        .HasConstraintName("FK__Animal__PadreId__7F2BE32F");

                    b.HasOne("AgroTechApp.Models.DB.Raza", "Raza")
                        .WithMany("Animals")
                        .HasForeignKey("RazaId")
                        .HasConstraintName("FK__Animal__RazaId__7B5B524B");

                    b.Navigation("Finca");

                    b.Navigation("LoteAnimal");

                    b.Navigation("Madre");

                    b.Navigation("Padre");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Gasto", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("Gastos")
                        .HasForeignKey("AnimalId")
                        .HasConstraintName("FK__Gasto__AnimalId__1CBC4616");

                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Gastos")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Gasto__FincaId__1AD3FDA4");

                    b.HasOne("AgroTechApp.Models.DB.Insumo", "Insumo")
                        .WithMany("Gastos")
                        .HasForeignKey("InsumoId")
                        .HasConstraintName("FK__Gasto__InsumoId__1EA48E88");

                    b.HasOne("AgroTechApp.Models.DB.Potrero", "Potrero")
                        .WithMany("Gastos")
                        .HasForeignKey("PotreroId")
                        .HasConstraintName("FK__Gasto__PotreroId__1DB06A4F");

                    b.HasOne("AgroTechApp.Models.DB.RubroGasto", "RubroGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("RubroGastoId")
                        .IsRequired()
                        .HasConstraintName("FK__Gasto__RubroGast__1BC821DD");

                    b.Navigation("Animal");

                    b.Navigation("Finca");

                    b.Navigation("Insumo");

                    b.Navigation("Potrero");

                    b.Navigation("RubroGasto");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Ingreso", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("Ingresos")
                        .HasForeignKey("AnimalId")
                        .HasConstraintName("FK__Ingreso__AnimalI__236943A5");

                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Ingresos")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingreso__FincaId__2180FB33");

                    b.HasOne("AgroTechApp.Models.DB.RubroIngreso", "RubroIngreso")
                        .WithMany("Ingresos")
                        .HasForeignKey("RubroIngresoId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingreso__RubroIn__22751F6C");

                    b.Navigation("Animal");

                    b.Navigation("Finca");

                    b.Navigation("RubroIngreso");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Insumo", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.CategoriaInsumo", "Categoria")
                        .WithMany("Insumos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Insumo__Categori__5EBF139D");

                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Insumos")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Insumo__FincaId__5DCAEF64");

                    b.HasOne("AgroTechApp.Models.DB.UnidadMedidum", "Unidad")
                        .WithMany("Insumos")
                        .HasForeignKey("UnidadId")
                        .IsRequired()
                        .HasConstraintName("FK__Insumo__UnidadId__5FB337D6");

                    b.Navigation("Categoria");

                    b.Navigation("Finca");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.InsumoLote", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Insumo", "Insumo")
                        .WithMany("InsumoLotes")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK__InsumoLot__Insum__656C112C");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.LoteAnimal", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("LoteAnimals")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__LoteAnima__Finca__70DDC3D8");

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Mortalidad", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("Mortalidads")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__Mortalida__Anima__1332DBDC");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.MovimientoAnimal", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("MovimientoAnimals")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__Anima__02FC7413");

                    b.HasOne("AgroTechApp.Models.DB.Potrero", "Potrero")
                        .WithMany("MovimientoAnimals")
                        .HasForeignKey("PotreroId")
                        .HasConstraintName("FK__Movimient__Potre__03F0984C");

                    b.Navigation("Animal");

                    b.Navigation("Potrero");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.MovimientoInventario", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__Finca__68487DD7");

                    b.HasOne("AgroTechApp.Models.DB.Insumo", "Insumo")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__Insum__693CA210");

                    b.HasOne("AgroTechApp.Models.DB.InsumoLote", "Lote")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("LoteId")
                        .HasConstraintName("FK__Movimient__LoteI__6A30C649");

                    b.HasOne("AgroTechApp.Models.DB.TipoMovimientoInventario", "Tipo")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("TipoId")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__TipoI__6B24EA82");

                    b.Navigation("Finca");

                    b.Navigation("Insumo");

                    b.Navigation("Lote");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.PeriodoRetiro", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Tratamiento", "Tratamiento")
                        .WithMany("PeriodoRetiros")
                        .HasForeignKey("TratamientoId")
                        .IsRequired()
                        .HasConstraintName("FK__PeriodoRe__Trata__0F624AF8");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Pesaje", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("Pesajes")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__Pesaje__AnimalId__17F790F9");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Potrero", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Potreros")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Potrero__FincaId__74AE54BC");

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Tratamiento", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Animal", "Animal")
                        .WithMany("Tratamientos")
                        .HasForeignKey("AnimalId")
                        .HasConstraintName("FK__Tratamien__Anima__08B54D69");

                    b.HasOne("AgroTechApp.Models.DB.Finca", "Finca")
                        .WithMany("Tratamientos")
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__Tratamien__Finca__06CD04F7");

                    b.HasOne("AgroTechApp.Models.DB.Insumo", "Insumo")
                        .WithMany("Tratamientos")
                        .HasForeignKey("InsumoId")
                        .HasConstraintName("FK__Tratamien__Insum__0B91BA14");

                    b.HasOne("AgroTechApp.Models.DB.LoteAnimal", "LoteAnimal")
                        .WithMany("Tratamientos")
                        .HasForeignKey("LoteAnimalId")
                        .HasConstraintName("FK__Tratamien__LoteA__09A971A2");

                    b.HasOne("AgroTechApp.Models.DB.InsumoLote", "Lote")
                        .WithMany("Tratamientos")
                        .HasForeignKey("LoteId")
                        .HasConstraintName("FK__Tratamien__LoteI__0C85DE4D");

                    b.HasOne("AgroTechApp.Models.DB.TipoTratamiento", "TipoTrat")
                        .WithMany("Tratamientos")
                        .HasForeignKey("TipoTratId")
                        .IsRequired()
                        .HasConstraintName("FK__Tratamien__TipoT__07C12930");

                    b.Navigation("Animal");

                    b.Navigation("Finca");

                    b.Navigation("Insumo");

                    b.Navigation("Lote");

                    b.Navigation("LoteAnimal");

                    b.Navigation("TipoTrat");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.User", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RolId__403A8C7D");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("UserFinca", b =>
                {
                    b.HasOne("AgroTechApp.Models.DB.Finca", null)
                        .WithMany()
                        .HasForeignKey("FincaId")
                        .IsRequired()
                        .HasConstraintName("FK__UserFinca__Finca__45F365D3");

                    b.HasOne("AgroTechApp.Models.DB.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserFinca__UserI__44FF419A");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Animal", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");

                    b.Navigation("InverseMadre");

                    b.Navigation("InversePadre");

                    b.Navigation("Mortalidads");

                    b.Navigation("MovimientoAnimals");

                    b.Navigation("Pesajes");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.CategoriaInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Finca", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");

                    b.Navigation("Insumos");

                    b.Navigation("LoteAnimals");

                    b.Navigation("MovimientoInventarios");

                    b.Navigation("Potreros");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Insumo", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("InsumoLotes");

                    b.Navigation("MovimientoInventarios");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.InsumoLote", b =>
                {
                    b.Navigation("MovimientoInventarios");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.LoteAnimal", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Potrero", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("MovimientoAnimals");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Raza", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.RubroGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.RubroIngreso", b =>
                {
                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.TipoMovimientoInventario", b =>
                {
                    b.Navigation("MovimientoInventarios");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.TipoTratamiento", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.Tratamiento", b =>
                {
                    b.Navigation("PeriodoRetiros");
                });

            modelBuilder.Entity("AgroTechApp.Models.DB.UnidadMedidum", b =>
                {
                    b.Navigation("Insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
